2019-09-14 12:18:37,594:DEBUG:certbot.main:certbot version: 0.37.1
2019-09-14 12:18:37,594:DEBUG:certbot.main:Arguments: ['--manual', '--preferred-challenges', 'dns', '--email', 'developer@anhminhltd.com', '--server', 'https://acme-v02.api.letsencrypt.org/directory', '--agree-tos', '--config-dir', '/Users/minh/Desktop/awesome/awesome-system/k8s/00-generic/certs-anhminhltd.com', '--work-dir', '/Users/minh/Desktop/awesome/awesome-system/k8s/00-generic/certs-anhminhltd.com', '--logs-dir', '/Users/minh/Desktop/awesome/awesome-system/k8s/00-generic/certs-anhminhltd.com', '-d', '*.anhminhltd.com']
2019-09-14 12:18:37,594:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2019-09-14 12:18:37,629:DEBUG:certbot.log:Root logging level set at 20
2019-09-14 12:18:37,629:INFO:certbot.log:Saving debug log to /Users/minh/Desktop/awesome/awesome-system/k8s/00-generic/certs-anhminhltd.com/letsencrypt.log
2019-09-14 12:18:37,630:DEBUG:certbot.plugins.selection:Requested authenticator manual and installer None
2019-09-14 12:18:37,634:DEBUG:certbot.plugins.selection:Single candidate plugin: * manual
Description: Manual configuration or run your own shell scripts
Interfaces: IAuthenticator, IPlugin
Entry point: manual = certbot.plugins.manual:Authenticator
Initialized: <certbot.plugins.manual.Authenticator object at 0x105b4d250>
Prep: True
2019-09-14 12:18:37,635:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.manual.Authenticator object at 0x105b4d250> and installer None
2019-09-14 12:18:37,635:INFO:certbot.plugins.selection:Plugins selected: Authenticator manual, Installer None
2019-09-14 12:18:37,640:DEBUG:certbot.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/56640403', new_authzr_uri=None, terms_of_service=None), 38787a764d1145de93b02e8c004e10c4, Meta(creation_dt=datetime.datetime(2019, 5, 8, 8, 48, 2, tzinfo=<UTC>), creation_host='Minhs-MacBook-Pro.local'))>
2019-09-14 12:18:37,657:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2019-09-14 12:18:37,755:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2019-09-14 12:18:38,921:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2019-09-14 12:18:38,921:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/json
Content-Length: 658
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Sat, 14 Sep 2019 05:19:31 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sat, 14 Sep 2019 05:19:31 GMT
Connection: keep-alive

{
  "dRA56BBoEO0": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2019-09-14 12:18:38,923:DEBUG:certbot.cert_manager:Renewal conf file /Users/minh/Desktop/awesome/awesome-system/k8s/00-generic/certs-anhminhltd.com/renewal/anhminhltd.com.conf is broken. Skipping.
2019-09-14 12:18:38,925:DEBUG:certbot.cert_manager:Traceback was:
Traceback (most recent call last):
  File "/usr/local/Cellar/certbot/0.37.1_1/libexec/lib/python3.7/site-packages/certbot/cert_manager.py", line 382, in _search_lineages
    candidate_lineage = storage.RenewableCert(renewal_file, cli_config)
  File "/usr/local/Cellar/certbot/0.37.1_1/libexec/lib/python3.7/site-packages/certbot/storage.py", line 466, in __init__
    self._check_symlinks()
  File "/usr/local/Cellar/certbot/0.37.1_1/libexec/lib/python3.7/site-packages/certbot/storage.py", line 524, in _check_symlinks
    "expected {0} to be a symlink".format(link))
certbot.errors.CertStorageError: expected /Users/minh/Desktop/ezlife/awesome-system/k8s/00-generic/certs-anhminhltd.com/live/anhminhltd.com/cert.pem to be a symlink

2019-09-14 12:18:38,925:INFO:certbot.main:Obtaining a new certificate
2019-09-14 12:18:39,038:DEBUG:certbot.crypto_util:Generating key (2048 bits): /Users/minh/Desktop/awesome/awesome-system/k8s/00-generic/certs-anhminhltd.com/keys/0002_key-certbot.pem
2019-09-14 12:18:39,040:DEBUG:certbot.crypto_util:Creating CSR: /Users/minh/Desktop/awesome/awesome-system/k8s/00-generic/certs-anhminhltd.com/csr/0002_csr-certbot.pem
2019-09-14 12:18:39,041:DEBUG:acme.client:Requesting fresh nonce
2019-09-14 12:18:39,041:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2019-09-14 12:18:39,321:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2019-09-14 12:18:39,322:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0001SER6sL-WJatBnLD7Tw7RbWtzHb91PsBzYy76NHFBSIM
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Content-Length: 0
Expires: Sat, 14 Sep 2019 05:19:32 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sat, 14 Sep 2019 05:19:32 GMT
Connection: keep-alive


2019-09-14 12:18:39,322:DEBUG:acme.client:Storing nonce: 0001SER6sL-WJatBnLD7Tw7RbWtzHb91PsBzYy76NHFBSIM
2019-09-14 12:18:39,322:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "*.anhminhltd.com"\n    }\n  ]\n}'
2019-09-14 12:18:39,325:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvNTY2NDA0MDMiLCAibm9uY2UiOiAiMDAwMVNFUjZzTC1XSmF0Qm5MRDdUdzdSYld0ekhiOTFQc0J6WXk3Nk5IRkJTSU0iLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "kKyamUeBL5VEem7Nupn6g02PwnYoBl1lcYvb4S03ybSIQSiBTa3_072PVXsVm0ZNBWSKVkymh8qx1nFAsU2adZryFlf2MosbjMUF1udMPFLXDerxPQ422n9P4r7NeTPubr8n5KJvgkdeBg6xm1q9anpM9RalPyzfzvnURebXHzfLI68gmmJGkT74uLWQj6Sv68vmdNzR3UAQdBZ691wkHOZlZJWvsrFIEnCbExaE6m5iFVYXBpk3iOCLHjT4zNoP4iUFygiSaxN_gsMHUeR2RCXy-K-bMCsAHwzC2OiAXFY-oYYjmzuSXCo8ENb_x9hKil51g5W80FlCzO_VaZMVtw",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogIiouYW5obWluaGx0ZC5jb20iCiAgICB9CiAgXQp9"
}
2019-09-14 12:18:39,760:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 345
2019-09-14 12:18:39,760:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Content-Type: application/json
Content-Length: 345
Boulder-Requester: 56640403
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/56640403/1084298571
Replay-Nonce: 0002pAkjAP9GqFx-k7O4r3h3RMst5bMWAi5kgt5yDw-oltQ
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Sat, 14 Sep 2019 05:19:32 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sat, 14 Sep 2019 05:19:32 GMT
Connection: keep-alive

{
  "status": "pending",
  "expires": "2019-09-21T05:19:32.420239913Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "*.anhminhltd.com"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/333793902"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/56640403/1084298571"
}
2019-09-14 12:18:39,760:DEBUG:acme.client:Storing nonce: 0002pAkjAP9GqFx-k7O4r3h3RMst5bMWAi5kgt5yDw-oltQ
2019-09-14 12:18:39,761:DEBUG:acme.client:JWS payload:
b''
2019-09-14 12:18:39,762:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/333793902:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvNTY2NDA0MDMiLCAibm9uY2UiOiAiMDAwMnBBa2pBUDlHcUZ4LWs3TzRyM2gzUk1zdDViTVdBaTVrZ3Q1eUR3LW9sdFEiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzMzMzc5MzkwMiJ9",
  "signature": "eXoUc_w121DZwdvrNTNgiRSxw218HwIYuBr7qhMmJvIwF73rULirx2exSCSw7q9GU7I5m0-5Dua5atye3PGd9QDY4IkfTZMZ-_Ce8uEB7A4K1Qwa6ZopuMbQ6iACvoIU-esbubVtvZnH8UpnNZKncnSpMVW4rw-FoCUB4kzR6GOsI_QT2RMq6G-B-5EPJIbqWj9gRuVZ9_QIGGOapT7KyUBUZmL9aQtugwDbNoZxI2pKM71AN8m2k8gce_1P83WBzm6k2laXEgLEyoVNFpByGtn747XVXo5mWn4z2SqlgWeI1MGCenm1gbt61mv1BsP4v-xRAinhX9hOm1qJ1F9JGg",
  "payload": ""
}
2019-09-14 12:18:40,063:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/333793902 HTTP/1.1" 200 385
2019-09-14 12:18:40,064:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/json
Content-Length: 385
Boulder-Requester: 56640403
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 00016YBNhR8kJ_DSfbGgq2U3l7UIH3aWy9sUm2t3GuRfGLE
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Sat, 14 Sep 2019 05:19:32 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sat, 14 Sep 2019 05:19:32 GMT
Connection: keep-alive

{
  "identifier": {
    "type": "dns",
    "value": "anhminhltd.com"
  },
  "status": "pending",
  "expires": "2019-09-21T05:19:32Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/333793902/mFzsBg",
      "token": "0lhYz9EZPY8TUl-ylo2zJ2TSlWhZPI5KhuwqrMYVCN0"
    }
  ],
  "wildcard": true
}
2019-09-14 12:18:40,064:DEBUG:acme.client:Storing nonce: 00016YBNhR8kJ_DSfbGgq2U3l7UIH3aWy9sUm2t3GuRfGLE
2019-09-14 12:18:40,065:INFO:certbot.auth_handler:Performing the following challenges:
2019-09-14 12:18:40,065:INFO:certbot.auth_handler:dns-01 challenge for anhminhltd.com
2019-09-14 12:18:44,960:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/local/Cellar/certbot/0.37.1_1/libexec/lib/python3.7/site-packages/certbot/auth_handler.py", line 69, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/local/Cellar/certbot/0.37.1_1/libexec/lib/python3.7/site-packages/certbot/plugins/manual.py", line 112, in perform
    self._verify_ip_logging_ok()
  File "/usr/local/Cellar/certbot/0.37.1_1/libexec/lib/python3.7/site-packages/certbot/plugins/manual.py", line 136, in _verify_ip_logging_ok
    raise errors.PluginError('Must agree to IP logging to proceed')
certbot.errors.PluginError: Must agree to IP logging to proceed

2019-09-14 12:18:44,960:DEBUG:certbot.error_handler:Calling registered functions
2019-09-14 12:18:44,960:INFO:certbot.auth_handler:Cleaning up challenges
2019-09-14 12:18:44,961:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.37.1', 'console_scripts', 'certbot')()
  File "/usr/local/Cellar/certbot/0.37.1_1/libexec/lib/python3.7/site-packages/certbot/main.py", line 1378, in main
    return config.func(config, plugins)
  File "/usr/local/Cellar/certbot/0.37.1_1/libexec/lib/python3.7/site-packages/certbot/main.py", line 1265, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/local/Cellar/certbot/0.37.1_1/libexec/lib/python3.7/site-packages/certbot/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/local/Cellar/certbot/0.37.1_1/libexec/lib/python3.7/site-packages/certbot/client.py", line 405, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/local/Cellar/certbot/0.37.1_1/libexec/lib/python3.7/site-packages/certbot/client.py", line 348, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/local/Cellar/certbot/0.37.1_1/libexec/lib/python3.7/site-packages/certbot/client.py", line 384, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/local/Cellar/certbot/0.37.1_1/libexec/lib/python3.7/site-packages/certbot/auth_handler.py", line 69, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/local/Cellar/certbot/0.37.1_1/libexec/lib/python3.7/site-packages/certbot/plugins/manual.py", line 112, in perform
    self._verify_ip_logging_ok()
  File "/usr/local/Cellar/certbot/0.37.1_1/libexec/lib/python3.7/site-packages/certbot/plugins/manual.py", line 136, in _verify_ip_logging_ok
    raise errors.PluginError('Must agree to IP logging to proceed')
certbot.errors.PluginError: Must agree to IP logging to proceed
